sonar.sources=.
sonar.tests=.
sonar.test.inclusions=packages/*/test/**,packages/*/e2e/**,packages/vscode/native/**
sonar.exclusions=packages/*/test/**,packages/*/e2e/**,packages/vscode/native/**,spikes/**,docs/**
