import { createHash } from "node:crypto";
import { DETECTORS, type Detector, type DetectorInput } from "./detectors.js";
import { languageForPath, type LanguageSpec } from "./languages.js";
import { applySplices, dominantEol, lineIndexAt, splitLines, type Line, type Splice } from "./lines.js";
import { freshId } from "./ids.js";
import { LITERAL_KEY, stringStatementAt } from "./literals.js";
import { ID_PATTERN, escapeRegExp } from "./markers.js";
import { findComments, parsesCleanly, type CommentNode } from "./parser.js";
import { normalizeBody, type Sidecar } from "./sidecar.js";

/** Why a comment is never a scan candidate. */
export type ProtectedClass = "doc" | "pragma" | "license" | "ticketed-todo" | "commented-out-code" | "unconvertible";

export interface Finding {
  detector: string;
  score: number;
}

export interface ScannedComment {
  /** Offset of the first comment token and just past the last one. */
  start: number;
  end: number;
  /** 1-based rows of the first and last token. */
  line: number;
  endLine: number;
  placement: "own-line" | "trailing";
  /** `string` is a Python string statement, found only by an explicit demote. */
  style: "line" | "block" | "string";
  /** For a string, its `literal` metadata (literals.ts). */
  literal?: string;
  /** Comment text without delimiters, LF-joined. */
  text: string;
  /** Hash of the whitespace-normalized text: how a reviewed list and the ignore file find a comment again. */
  fingerprint: string;
  protected: ProtectedClass | undefined;
  findings: Finding[];
  /** Noisy-or of the findings' scores; 0 when there are none. */
  score: number;
  /** Token spans; a group of own-line line comments has one per line. */
  spans: { start: number; end: number }[];
  indent: string;
}

interface Token {
  start: number;
  end: number;
  row: number;
  endRow: number;
  raw: string;
  style: "line" | "block";
  /** Leading whitespace when the token starts its line. */
  indent: string | undefined;
  codeAfter: boolean;
  parentType: string | undefined;
  /** Delimiter-free text; for a line token, one line. */
  lines: string[];
}

/** Tokens scan reports as one comment. `protection` is set when a token alone decided it. */
interface TokenGroup {
  tokens: Token[];
  protection: ProtectedClass | undefined;
}

/** What analyzing one group needs to know about its file. */
interface FileContext {
  spec: LanguageSpec;
  source: string;
  lines: Line[];
  /** Rows covered by own-line comments, which `nextCodeLine` skips. */
  commentRows: Set<number>;
  /** Offset of the first byte that is neither whitespace nor comment: license headers sit before it. */
  firstCode: number;
  detectors: readonly Detector[];
}

function lineText(raw: string): string {
  const rest = raw.replace(/^(?:\/\/|#)/, "");
  return (rest.startsWith(" ") ? rest.slice(1) : rest).trimEnd();
}

function blockLines(raw: string): string[] {
  const lines = raw
    .slice(2, raw.endsWith("*/") ? -2 : undefined)
    .split(/\r?\n/)
    .map((l, i) => (i === 0 ? l : l.replace(/^\s*\*? ?/, "")).trimEnd());
  if (lines.length) lines[0] = lines[0]!.replace(/^[*!]?\s*/, "");
  return trimBlankEnds(lines, (l) => !l);
}

// Tool directives a comment can start with.
const PRAGMA_OPENERS = [
  /eslint(?:-disable|-enable|-env)?\b/, /globals?\s/, /jshint\b/, /jslint\b/, /istanbul\s/, /c8\s/, /v8\s/,
  /prettier-ignore/, /biome-ignore/, /deno-(?:lint|fmt)-ignore/, /tslint:/,
  /@ts-/, /@jsx/, /@flow/, /@noflow/, /@format/, /@refresh/, /@vite-ignore/,
  /@license/, /@preserve/, /@generated/, /webpack[A-Z]/, /#__PURE__/, /@__PURE__/, /\$FlowFixMe/,
  /noinspection\b/, /resharper\s/, /nosonar\b/, /checkstyle:/, /@formatter:/, /language=/,
  /cspell:/, /spell-checker:/, /stylelint-/, /[#@] ?sourceMappingURL=/,
  /#?region\b/, /#?endregion\b/, /<\/?editor-fold/,
  /fmt:\s/, /isort:/, /mypy:/, /pyright:/, /pylint:/, /ruff:/, /yapf:/, /type:\s/, /noqa\b/, /nosec\b/,
  /pragma\b/, /nolint\b/, /lgtm\b/, /codeql\b/, /clang-format\b/, /keep-sorted\b/, /ktlint-(?:disable|enable)\b/,
  /<auto-generated/, /auto-generated/, /code generated/, /do not edit/, /-\*-/, /vim?:/, /coding[:=]/,
];
const PRAGMA_OPENER = new RegExp(`^(?:${PRAGMA_OPENERS.map((r) => r.source).join("|")})`, "i");
const PRAGMA_ANYWHERE =
  /\b(?:noqa|nosec|NOSONAR|NOLINT(?:NEXTLINE)?|eslint-disable(?:-next-line|-line)?|@ts-(?:ignore|expect-error|nocheck)|pylint: ?disable|pragma: no cover|type: ?ignore|istanbul ignore|c8 ignore|CHECKSTYLE:(?:ON|OFF)|ReSharper disable)\b/;
const LICENSE = /\bSPDX-License-Identifier\b|\bcopyright\b|\blicen[cs]ed?\b|\(c\)\s*\d{4}|©|all rights reserved/i;
// Below the first line of code, a license mention protects a comment only with one of these.
const EXPLICIT_LICENSE = /SPDX-License-Identifier|copyright/i;
const TICKETED_TODO = /^(?:TODO|FIXME|XXX|HACK|BUG)\b\s*(?:\([^)]*\)|[:-]?\s*(?:[A-Z][A-Z0-9]+-\d+|#\d+|https?:\/\/|@\w))/i;
// Only lines with code punctuation or a leading keyword go to the parser.
const CODE_SHAPED = /[;{}()[\]=]|^(?:import|from|return|def|class|const|let|var|function|if|for|while|print|await|async|public|private|protected|static|using|namespace|package|throw|raise|try|new|val|fun|override)\b/;

/** Protection decided by one token alone; these also break a group of line comments. */
function tokenProtection(t: Token): ProtectedClass | undefined {
  if (t.row === 0 && t.raw.startsWith("#!")) return "pragma";
  const text = t.lines.join(" ");
  // Before the doc test: `/// <reference ... />` is a directive that looks like a C# doc line.
  if (/^\/\/\/\s*<(?:reference|amd-)/.test(t.raw)) return "pragma";
  if (t.style === "block" ? /^\/\*\*(?!\/)/.test(t.raw) : /^\/\/[/!]/.test(t.raw)) return "doc";
  if (PRAGMA_OPENER.test(text) || PRAGMA_ANYWHERE.test(text) || t.raw.startsWith("/*!")) {
    return LICENSE.test(text) ? "license" : "pragma";
  }
  // A block with code after it on its line (an inline argument, JSX) has no line-sigil form.
  if (t.codeAfter || t.parentType?.startsWith("jsx")) return "unconvertible";
  return undefined;
}

async function looksLikeCode(spec: LanguageSpec, line: string): Promise<boolean> {
  const trimmed = line.trim();
  return CODE_SHAPED.test(trimmed) && (await parsesCleanly(spec, trimmed));
}

async function groupProtection(spec: LanguageSpec, lines: string[], beforeCode: boolean): Promise<ProtectedClass | undefined> {
  const text = lines.join(" ");
  if (LICENSE.test(text) && (beforeCode || EXPLICIT_LICENSE.test(text))) return "license";
  if (TICKETED_TODO.test(lines[0] ?? "")) return "ticketed-todo";
  for (const line of lines) {
    if (await looksLikeCode(spec, line)) return "commented-out-code";
  }
  return undefined;
}

export function fingerprintOf(text: string): string {
  const normalized = text.replace(/\s+/g, " ").trim();
  return createHash("sha256").update(normalized).digest("hex").slice(0, 8);
}

function noisyOr(scores: number[]): number {
  return 1 - scores.reduce((p, s) => p * (1 - s), 1);
}

/** `items` without the blank entries at either end. */
function trimBlankEnds<T>(items: T[], isBlank: (item: T) => boolean): T[] {
  let start = 0;
  let end = items.length;
  while (start < end && isBlank(items[start]!)) start++;
  while (end > start && isBlank(items[end - 1]!)) end--;
  return items.slice(start, end);
}

function tokenize(source: string, lines: Line[], nodes: CommentNode[]): Token[] {
  return nodes.map((n) => {
    // Some grammars (Python's) let the comment token swallow the CR of a CRLF terminator.
    const raw = source.slice(n.start, n.end).replace(/\r$/, "");
    const end = n.start + raw.length;
    const row = lineIndexAt(lines, n.start);
    const endRow = lineIndexAt(lines, end);
    const before = source.slice(lines[row]!.start, n.start);
    const style = raw.startsWith("/*") ? "block" : "line";
    return {
      start: n.start,
      end,
      row,
      endRow,
      raw,
      style,
      indent: /^[ \t]*$/.test(before) ? before : undefined,
      codeAfter: source.slice(end, lines[endRow]!.contentEnd).trim() !== "",
      parentType: n.parentType,
      lines: style === "block" ? blockLines(raw) : [lineText(raw)],
    };
  });
}

function firstCodeOffset(source: string, tokens: Token[]): number {
  let commentsEnd = 0;
  for (const t of tokens) {
    if (source.slice(commentsEnd, t.start).trim()) break;
    commentsEnd = t.end;
  }
  const code = source.slice(commentsEnd).search(/\S/);
  return code < 0 ? source.length : commentsEnd + code;
}

function ownLineCommentRows(tokens: Token[]): Set<number> {
  const rows = new Set<number>();
  for (const t of tokens) {
    if (t.indent === undefined) continue;
    for (let row = t.row; row <= t.endRow; row++) rows.add(row);
  }
  return rows;
}

/** The tokens from `start` on, for as long as each one continues the one before it. */
function takeRun(tokens: Token[], start: number, continues: (prev: Token, next: Token) => boolean): Token[] {
  let end = start + 1;
  while (end < tokens.length && continues(tokens[end - 1]!, tokens[end]!)) end++;
  return tokens.slice(start, end);
}

/**
 * Groups tokens the way a sigil block groups: consecutive own-line line comments at one
 * indent. A run of one protected class (a `///` doc block, stacked pragmas) forms its own
 * group. Existing sigil comments are skipped: they are already managed.
 */
function groupTokens(tokens: Token[], sigil: string): TokenGroup[] {
  const isSigil = (t: Token) => t.raw.startsWith(sigil);
  const directlyBelow = (prev: Token, next: Token) => next.indent === prev.indent && next.row === prev.row + 1;
  const continuesProtected = (prev: Token, next: Token) =>
    directlyBelow(prev, next) && tokenProtection(next) === tokenProtection(prev);
  const continuesComment = (prev: Token, next: Token) =>
    next.style === "line" && directlyBelow(prev, next) && !isSigil(next) && !tokenProtection(next);

  const groups: TokenGroup[] = [];
  let i = 0;
  while (i < tokens.length) {
    const first = tokens[i]!;
    const protection = tokenProtection(first);
    if (isSigil(first)) {
      i++;
    } else if (first.style === "block" || first.indent === undefined) {
      if (first.lines.length) groups.push({ tokens: [first], protection });
      i++;
    } else if (protection) {
      const run = takeRun(tokens, i, continuesProtected);
      groups.push({ tokens: run, protection });
      i += run.length;
    } else {
      const run = takeRun(tokens, i, continuesComment);
      // Blank comment lines at either end stay as they are.
      const kept = trimBlankEnds(run, (t) => !t.lines[0]);
      if (kept.length) groups.push({ tokens: kept, protection: undefined });
      i += run.length;
    }
  }
  return groups;
}

/** The first line of code below `row`, trimmed; empty when there is none. */
function nextCodeLine(file: FileContext, row: number): string {
  for (let r = row + 1; r < file.lines.length; r++) {
    const line = file.lines[r]!;
    const content = file.source.slice(line.start, line.contentEnd).trim();
    if (content && !file.commentRows.has(r)) return content;
  }
  return "";
}

async function analyzeGroup(file: FileContext, group: TokenGroup): Promise<ScannedComment> {
  const first = group.tokens[0]!;
  const last = group.tokens[group.tokens.length - 1]!;
  const textLines = group.tokens.flatMap((t) => t.lines);
  const text = textLines.join("\n");
  const placement = first.indent !== undefined ? "own-line" : "trailing";
  const protection = group.protection ?? (await groupProtection(file.spec, textLines, first.start < file.firstCode));

  let findings: Finding[] = [];
  if (!protection) {
    const input: DetectorInput = {
      text: textLines.join(" "),
      firstLine: textLines[0] ?? "",
      lineCount: textLines.length,
      placement,
      context:
        placement === "own-line"
          ? nextCodeLine(file, last.endRow)
          : file.source.slice(file.lines[first.row]!.start, first.start).trim(),
    };
    findings = file.detectors.filter((d) => d.test(input)).map((d) => ({ detector: d.name, score: d.score }));
  }

  return {
    start: first.start,
    end: last.end,
    line: first.row + 1,
    endLine: last.endRow + 1,
    placement,
    style: first.style,
    text,
    fingerprint: fingerprintOf(text),
    protected: protection,
    findings,
    score: noisyOr(findings.map((f) => f.score)),
    spans: group.tokens.map((t) => ({ start: t.start, end: t.end })),
    indent: first.indent ?? "",
  };
}

export interface ScanOptions {
  /** Detectors to run; the enabled ones by default. */
  detectors?: readonly Detector[];
}

/** Every comment in `source` that is not already a sigil comment, with its protection and detector findings. */
export async function analyzeSource(path: string, source: string, options: ScanOptions = {}): Promise<ScannedComment[]> {
  const spec = languageForPath(path);
  if (!spec) return [];
  const lines = splitLines(source);
  const tokens = tokenize(source, lines, await findComments(spec, source));
  const file: FileContext = {
    spec,
    source,
    lines,
    commentRows: ownLineCommentRows(tokens),
    firstCode: firstCodeOffset(source, tokens),
    detectors: options.detectors ?? DETECTORS.filter((d) => d.enabled),
  };
  const comments: ScannedComment[] = [];
  for (const group of groupTokens(tokens, spec.lineSigil)) comments.push(await analyzeGroup(file, group));
  return comments;
}

/** Unprotected comments with at least one finding, in file order. */
export async function scanSource(path: string, source: string, options: ScanOptions = {}): Promise<ScannedComment[]> {
  return (await analyzeSource(path, source, options)).filter((c) => !c.protected && c.findings.length);
}

/** Units a comment is matched by: one per line of a line-comment group, the whole text of a block. */
function unitsOf(c: ScannedComment): string[] {
  return c.style === "line" ? c.text.split("\n").map((l) => `line\0${l}`) : [`block\0${c.text}`];
}

/** Indices of each maximal run of `true` in `flags`. */
function runsOf(flags: boolean[]): number[][] {
  const runs: number[][] = [];
  flags.forEach((flag, i) => {
    if (!flag) return;
    if (flags[i - 1]) runs[runs.length - 1]!.push(i);
    else runs.push([i]);
  });
  return runs;
}

/**
 * Unprotected comments in `source` that `baseline` (the same file as last staged) does
 * not have: what `tag` turns into sigil comments. A line comment is matched line by line,
 * so a line an agent appends to a human comment is new on its own and the human lines
 * stay as written; an edited line or block counts as new. Matching is a multiset, so a
 * duplicated comment is new once.
 */
export async function newComments(path: string, source: string, baseline: string): Promise<ScannedComment[]> {
  const known = new Map<string, number>();
  for (const c of await analyzeSource(path, baseline, { detectors: [] })) {
    for (const unit of unitsOf(c)) known.set(unit, (known.get(unit) ?? 0) + 1);
  }
  const seen = (unit: string): boolean => {
    const n = known.get(unit) ?? 0;
    if (n) known.set(unit, n - 1);
    return n > 0;
  };

  const out: ScannedComment[] = [];
  for (const c of await analyzeSource(path, source, { detectors: [] })) {
    const fresh = unitsOf(c).map((u) => !seen(u));
    if (c.protected || !fresh.some(Boolean)) continue;
    if (fresh.every(Boolean)) {
      out.push(c);
      continue;
    }
    // Runs of new lines inside an existing group become comments of their own.
    const lines = c.text.split("\n");
    for (const run of runsOf(fresh)) {
      const rows = trimBlankEnds(run, (i) => !lines[i]);
      if (!rows.length) continue;
      const text = rows.map((i) => lines[i]).join("\n");
      const spans = rows.map((i) => c.spans[i]!);
      out.push({
        ...c,
        start: spans[0]!.start,
        end: spans[spans.length - 1]!.end,
        line: c.line + rows[0]!,
        endLine: c.line + rows[rows.length - 1]!,
        text,
        fingerprint: fingerprintOf(text),
        spans,
      });
    }
  }
  return out;
}

/** Classes that only keep scan from proposing a comment; an explicit demote overrides them. */
const SCAN_ONLY_PROTECTION = new Set<ProtectedClass>(["ticketed-todo", "commented-out-code"]);

/**
 * The comment an explicit demote of 1-based `line` would convert, or why there is none:
 * no comment there, a sigil comment already, or a class whose meaning depends on staying
 * in the code (doc, pragma, license, a docstring) or that has no line-sigil form. A Python
 * string statement that is not a docstring counts as a comment here.
 */
export async function demoteTarget(path: string, source: string, line: number): Promise<ScannedComment | string> {
  const spec = languageForPath(path);
  if (!spec) return "not a supported language";
  const found = (await analyzeSource(path, source, { detectors: [] })).find((c) => c.line <= line && line <= c.endLine);
  if (!found) {
    const string = await stringStatementAt(spec, source, line - 1);
    if (typeof string === "string") return string;
    if (string) {
      const text = string.lines.join("\n");
      return {
        start: string.start,
        end: string.end,
        line: string.row + 1,
        endLine: string.endRow + 1,
        placement: "own-line",
        style: "string",
        literal: string.literal,
        text: normalizeBody(text),
        fingerprint: fingerprintOf(text),
        protected: undefined,
        findings: [],
        score: 0,
        spans: [{ start: string.start, end: string.end }],
        indent: string.indent,
      };
    }
    const row = splitLines(source)[line - 1];
    const text = row ? source.slice(row.start, row.contentEnd) : "";
    return text.includes(spec.lineSigil) ? "already an AI comment" : "no comment on this line";
  }
  if (found.protected && !SCAN_ONLY_PROTECTION.has(found.protected)) return `a ${found.protected} comment stays in the code`;
  return { ...found, protected: undefined };
}

/**
 * Rewrites `comments` as new sigil comments (`<sigil> text`), which `sync` then stamps
 * with ids. Every byte outside the rewritten tokens, including each terminator, is kept;
 * a block comment becomes one sigil line per text line at the block's indent.
 */
export function convertComments(path: string, source: string, comments: readonly ScannedComment[]): string {
  return convert(path, source, comments, () => {
    throw new Error(`a string statement converts only through convertDemoted (${path})`);
  });
}

export interface DemoteConversion {
  source: string;
  /** Each converted string's new id and its `literal` metadata, for `recordLiterals` once synced. */
  literals: Map<string, string>;
}

/**
 * `convertComments` for an explicit demote, which can include Python string statements. A
 * string becomes a sigil block stamped with a fresh id (not in `taken`, the sidecar's ids,
 * nor in the source), so its quotes and layout can be recorded on the entry `sync` makes.
 */
export function convertDemoted(path: string, source: string, comments: readonly ScannedComment[], taken: ReadonlySet<string>): DemoteConversion {
  const spec = languageForPath(path);
  const inSource = spec ? [...source.matchAll(new RegExp(`${escapeRegExp(spec.lineSigil)}(${ID_PATTERN})`, "g"))].map((m) => m[1]!) : [];
  const used = new Set([...taken, ...inSource]);
  const literals = new Map<string, string>();
  const converted = convert(path, source, comments, (c) => {
    const id = freshId(path, c.text, used);
    literals.set(id, c.literal!);
    return id;
  });
  return { source: converted, literals };
}

/** `sidecar` with each converted string's `literal` metadata on its entry. */
export function recordLiterals(sidecar: Sidecar, literals: ReadonlyMap<string, string>): Sidecar {
  const entries = sidecar.entries.map((e) => {
    const literal = literals.get(e.id);
    return literal === undefined ? e : { ...e, meta: new Map([...e.meta, [LITERAL_KEY, literal]]) };
  });
  return { preamble: sidecar.preamble, entries };
}

function convert(path: string, source: string, comments: readonly ScannedComment[], stringId: (c: ScannedComment) => string): string {
  const spec = languageForPath(path);
  if (!spec) return source;
  const toSigil = (text: string) => (text ? `${spec.lineSigil} ${text}` : spec.lineSigil);
  const lines = splitLines(source);
  const fallbackEol = dominantEol(source);
  const splices: Splice[] = [];
  const eolOf = (c: ScannedComment) => {
    const row = lines[lineIndexAt(lines, c.start)]!;
    return row.end > row.contentEnd ? source.slice(row.contentEnd, row.end) : fallbackEol;
  };
  for (const c of comments) {
    if (c.protected) throw new Error(`refusing to convert a protected comment (${c.protected}) at ${path}:${c.line}`);
    if (c.style === "string") {
      const [head, ...rest] = c.text.split("\n");
      const block = [`${spec.lineSigil}${stringId(c)} ${head!}`, ...rest.map((l) => c.indent + toSigil(l))];
      splices.push({ start: c.start, end: c.end, text: block.join(eolOf(c)) });
      continue;
    }
    if (c.style === "line") {
      for (const span of c.spans) splices.push({ ...span, text: toSigil(lineText(source.slice(span.start, span.end))) });
      continue;
    }
    const body = blockLines(source.slice(c.start, c.end));
    if (c.placement === "trailing") {
      splices.push({ start: c.start, end: c.end, text: toSigil(body.join(" ")) });
      continue;
    }
    splices.push({ start: c.start, end: c.end, text: body.map(toSigil).join(eolOf(c) + c.indent) });
  }
  return applySplices(source, splices);
}
