import { createHash } from "node:crypto";
import { DETECTORS, type Detector } from "./detectors.js";
import { languageForPath, type LanguageSpec } from "./languages.js";
import { applySplices, dominantEol, lineIndexAt, splitLines, type Splice } from "./lines.js";
import { findComments, parsesCleanly } from "./parser.js";

/** Why a comment is never a scan candidate (plan A5). */
export type ProtectedClass = "doc" | "pragma" | "license" | "ticketed-todo" | "commented-out-code" | "unconvertible";

export interface Finding {
  detector: string;
  score: number;
}

export interface ScannedComment {
  /** Offset of the first comment token and just past the last one. */
  start: number;
  end: number;
  /** 1-based rows of the first and last token. */
  line: number;
  endLine: number;
  placement: "own-line" | "trailing";
  style: "line" | "block";
  /** Comment text without delimiters, LF-joined. */
  text: string;
  /** Hash of the whitespace-normalized text: how a reviewed list and the ignore file find a comment again. */
  fingerprint: string;
  protected: ProtectedClass | undefined;
  findings: Finding[];
  /** Noisy-or of the findings' scores; 0 when there are none. */
  score: number;
  /** Token spans; a group of own-line line comments has one per line. */
  spans: { start: number; end: number }[];
  indent: string;
}

interface Token {
  start: number;
  end: number;
  row: number;
  endRow: number;
  raw: string;
  style: "line" | "block";
  /** Leading whitespace when the token starts its line. */
  indent: string | undefined;
  codeAfter: boolean;
  parentType: string | undefined;
  /** Delimiter-free text; for a line token, one line. */
  lines: string[];
}

function lineText(raw: string): string {
  const rest = raw.replace(/^(?:\/\/|#)/, "");
  return (rest.startsWith(" ") ? rest.slice(1) : rest).trimEnd();
}

function blockLines(raw: string): string[] {
  const lines = raw
    .slice(2, raw.endsWith("*/") ? -2 : undefined)
    .split(/\r?\n/)
    .map((l, i) => (i === 0 ? l : l.replace(/^\s*\*? ?/, "")).trimEnd());
  if (lines.length) lines[0] = lines[0]!.replace(/^[*!]?\s*/, "");
  while (lines.length && !lines[0]) lines.shift();
  while (lines.length && !lines[lines.length - 1]) lines.pop();
  return lines;
}

const PRAGMA_OPENER =
  /^(?:eslint(?:-disable|-enable|-env)?\b|globals?\s|jshint\b|jslint\b|istanbul\s|c8\s|v8\s|prettier-ignore|biome-ignore|deno-(?:lint|fmt)-ignore|tslint:|@ts-|@jsx|@flow|@noflow|@format|@refresh|@vite-ignore|@license|@preserve|@generated|webpack[A-Z]|#__PURE__|@__PURE__|\$FlowFixMe|noinspection\b|resharper\s|nosonar\b|checkstyle:|@formatter:|language=|cspell:|spell-checker:|stylelint-|[#@] ?sourceMappingURL=|#?region\b|#?endregion\b|<\/?editor-fold|fmt:\s|isort:|mypy:|pyright:|pylint:|ruff:|yapf:|type:\s|noqa\b|nosec\b|pragma\b|nolint\b|lgtm\b|codeql\b|clang-format\b|keep-sorted\b|<auto-generated|auto-generated|code generated|do not edit|-\*-|vim?:|coding[:=])/i;
const PRAGMA_ANYWHERE =
  /\b(?:noqa|nosec|NOSONAR|NOLINT(?:NEXTLINE)?|eslint-disable(?:-next-line|-line)?|@ts-(?:ignore|expect-error|nocheck)|pylint: ?disable|pragma: no cover|type: ?ignore|istanbul ignore|c8 ignore|CHECKSTYLE:(?:ON|OFF)|ReSharper disable)\b/;
const LICENSE = /\bSPDX-License-Identifier\b|\bcopyright\b|\blicen[cs]ed?\b|\(c\)\s*\d{4}|©|all rights reserved/i;
const TICKETED_TODO = /^(?:TODO|FIXME|XXX|HACK|BUG)\b\s*(?:\([^)]*\)|[:-]?\s*(?:[A-Z][A-Z0-9]+-\d+|#\d+|https?:\/\/|@\w))/i;
// Only lines with code punctuation or a leading keyword go to the parser.
const CODE_SHAPED = /[;{}()[\]=]|^(?:import|from|return|def|class|const|let|var|function|if|for|while|print|await|async|public|private|protected|static|using|namespace|package|throw|raise|try|new)\b/;

/** Protection decided by one token alone; these also break a group of line comments. */
function tokenProtection(t: Token): ProtectedClass | undefined {
  if (t.row === 0 && t.raw.startsWith("#!")) return "pragma";
  const text = t.lines.join(" ");
  // Before the doc test: `/// <reference ... />` is a directive that looks like a C# doc line.
  if (/^\/\/\/\s*<(?:reference|amd-)/.test(t.raw)) return "pragma";
  if (t.style === "block" ? /^\/\*\*(?!\/)/.test(t.raw) : /^\/\/[/!]/.test(t.raw)) return "doc";
  if (PRAGMA_OPENER.test(text) || PRAGMA_ANYWHERE.test(text) || t.raw.startsWith("/*!")) {
    return LICENSE.test(text) ? "license" : "pragma";
  }
  // A block with code after it on its line (an inline argument, JSX) has no line-sigil form.
  if (t.codeAfter || t.parentType?.startsWith("jsx")) return "unconvertible";
  return undefined;
}

async function looksLikeCode(spec: LanguageSpec, line: string): Promise<boolean> {
  const trimmed = line.trim();
  return CODE_SHAPED.test(trimmed) && (await parsesCleanly(spec, trimmed));
}

async function groupProtection(spec: LanguageSpec, lines: string[], beforeCode: boolean): Promise<ProtectedClass | undefined> {
  const text = lines.join(" ");
  if (LICENSE.test(text) && (beforeCode || /SPDX-License-Identifier|copyright/i.test(text))) return "license";
  if (TICKETED_TODO.test(lines[0] ?? "")) return "ticketed-todo";
  for (const line of lines) if (await looksLikeCode(spec, line)) return "commented-out-code";
  return undefined;
}

export function fingerprintOf(text: string): string {
  const normalized = text.replace(/\s+/g, " ").trim();
  return createHash("sha256").update(normalized).digest("hex").slice(0, 8);
}

function noisyOr(scores: number[]): number {
  return 1 - scores.reduce((p, s) => p * (1 - s), 1);
}

export interface ScanOptions {
  /** Detectors to run; the enabled ones by default. */
  detectors?: readonly Detector[];
}

/**
 * Every comment in `source`, grouped the way a sigil block groups (consecutive own-line
 * line comments at one indent), with its protection and detector findings. Existing sigil
 * comments are skipped: they are already managed.
 */
export async function analyzeSource(path: string, source: string, options: ScanOptions = {}): Promise<ScannedComment[]> {
  const spec = languageForPath(path);
  if (!spec) return [];
  const detectors = options.detectors ?? DETECTORS.filter((d) => d.enabled);
  const lines = splitLines(source);
  const nodes = await findComments(spec, source);

  const tokens: Token[] = nodes.map((n) => {
    // Some grammars (Python's) let the comment token swallow the CR of a CRLF terminator.
    const raw = source.slice(n.start, n.end).replace(/\r$/, "");
    const end = n.start + raw.length;
    const row = lineIndexAt(lines, n.start);
    const endRow = lineIndexAt(lines, end);
    const before = source.slice(lines[row]!.start, n.start);
    const style = raw.startsWith("/*") ? "block" : "line";
    return {
      start: n.start,
      end,
      row,
      endRow,
      raw,
      style,
      indent: /^[ \t]*$/.test(before) ? before : undefined,
      codeAfter: source.slice(end, lines[endRow]!.contentEnd).trim() !== "",
      parentType: n.parentType,
      lines: style === "block" ? blockLines(raw) : [lineText(raw)],
    };
  });

  // Offset of the first byte that is neither whitespace nor comment: license headers sit before it.
  let firstCode = 0;
  for (const t of tokens) {
    if (source.slice(firstCode, t.start).trim()) break;
    firstCode = t.end;
  }
  if (!source.slice(firstCode).trim()) firstCode = source.length;
  else firstCode += source.slice(firstCode).search(/\S/);

  const commentRows = new Set<number>();
  for (const t of tokens) if (t.indent !== undefined) for (let r = t.row; r <= t.endRow; r++) commentRows.add(r);
  const nextCodeLine = (row: number): string => {
    for (let r = row + 1; r < lines.length; r++) {
      const l = lines[r]!;
      const content = source.slice(l.start, l.contentEnd).trim();
      if (content && !commentRows.has(r)) return content;
    }
    return "";
  };

  const out: ScannedComment[] = [];
  const emit = async (group: Token[], protection: ProtectedClass | undefined) => {
    const first = group[0]!;
    const last = group[group.length - 1]!;
    const textLines = group.flatMap((t) => t.lines);
    const placement = first.indent !== undefined ? "own-line" : "trailing";
    const text = textLines.join("\n");
    const prot = protection ?? (await groupProtection(spec, textLines, first.start < firstCode));
    const context = placement === "own-line" ? nextCodeLine(last.endRow) : source.slice(lines[first.row]!.start, first.start).trim();
    const findings = prot
      ? []
      : detectors
          .filter((d) =>
            d.test({ text: textLines.join(" "), firstLine: textLines[0] ?? "", lineCount: textLines.length, placement, context }),
          )
          .map((d) => ({ detector: d.name, score: d.score }));
    out.push({
      start: first.start,
      end: last.end,
      line: first.row + 1,
      endLine: last.endRow + 1,
      placement,
      style: first.style,
      text,
      fingerprint: fingerprintOf(text),
      protected: prot,
      findings,
      score: noisyOr(findings.map((f) => f.score)),
      spans: group.map((t) => ({ start: t.start, end: t.end })),
      indent: first.indent ?? "",
    });
  };

  const isSigil = (t: Token) => t.raw.startsWith(spec.lineSigil);
  for (let i = 0; i < tokens.length; i++) {
    const t = tokens[i]!;
    if (isSigil(t)) continue;
    const hard = tokenProtection(t);
    if (hard && t.style === "line" && t.indent !== undefined) {
      // A `///` doc block or a run of pragmas reports as one protected group.
      const group = [t];
      for (let next = tokens[i + 1]; next; next = tokens[i + 1]) {
        if (next.indent !== t.indent || next.row !== group[group.length - 1]!.row + 1 || tokenProtection(next) !== hard) break;
        group.push(next);
        i++;
      }
      await emit(group, hard);
      continue;
    }
    if (hard || t.style === "block" || t.indent === undefined) {
      if (t.lines.length) await emit([t], hard);
      continue;
    }
    // Own-line line comments: extend while the next one sits directly below at the same indent.
    const group = [t];
    for (let next = tokens[i + 1]; next; next = tokens[i + 1]) {
      const prev = group[group.length - 1]!;
      if (next.style !== "line" || next.indent !== t.indent || next.row !== prev.row + 1 || isSigil(next)) break;
      if (tokenProtection(next)) break;
      group.push(next);
      i++;
    }
    // Blank comment lines at either end stay as they are.
    while (group.length && !group[0]!.lines[0]) group.shift();
    while (group.length && !group[group.length - 1]!.lines[0]) group.pop();
    if (group.length) await emit(group, undefined);
  }
  return out;
}

/** Unprotected comments with at least one finding, highest score first within the file order. */
export async function scanSource(path: string, source: string, options: ScanOptions = {}): Promise<ScannedComment[]> {
  return (await analyzeSource(path, source, options)).filter((c) => !c.protected && c.findings.length);
}

/** Units a comment is matched by: one per line of a line-comment group, the whole text of a block. */
function unitsOf(c: ScannedComment): string[] {
  return c.style === "line" ? c.text.split("\n").map((l) => `line\0${l}`) : [`block\0${c.text}`];
}

/**
 * Unprotected comments in `source` that `baseline` (the same file as last staged) does
 * not have: what `tag` turns into sigil comments. A line comment is matched line by line,
 * so a line an agent appends to a human comment is new on its own and the human lines
 * stay as written; an edited line or block counts as new. Matching is a multiset, so a
 * duplicated comment is new once.
 */
export async function newComments(path: string, source: string, baseline: string): Promise<ScannedComment[]> {
  const known = new Map<string, number>();
  for (const c of await analyzeSource(path, baseline, { detectors: [] })) {
    for (const unit of unitsOf(c)) known.set(unit, (known.get(unit) ?? 0) + 1);
  }
  const seen = (unit: string): boolean => {
    const n = known.get(unit) ?? 0;
    if (n) known.set(unit, n - 1);
    return n > 0;
  };

  const out: ScannedComment[] = [];
  for (const c of await analyzeSource(path, source, { detectors: [] })) {
    const fresh = unitsOf(c).map((u) => !seen(u));
    if (c.protected || !fresh.some(Boolean)) continue;
    if (fresh.every(Boolean)) {
      out.push(c);
      continue;
    }
    // Runs of new lines inside an existing group become comments of their own.
    const lines = c.text.split("\n");
    for (let i = 0; i < lines.length; i++) {
      if (!fresh[i] || !lines[i]) continue;
      let j = i;
      while (j + 1 < lines.length && fresh[j + 1]) j++;
      while (!lines[j]) j--;
      const text = lines.slice(i, j + 1).join("\n");
      const spans = c.spans.slice(i, j + 1);
      out.push({
        ...c,
        start: spans[0]!.start,
        end: spans[spans.length - 1]!.end,
        line: c.line + i,
        endLine: c.line + j,
        text,
        fingerprint: fingerprintOf(text),
        spans,
      });
      i = j;
    }
  }
  return out;
}

/**
 * Rewrites `comments` as new sigil comments (`<sigil> text`), which `sync` then stamps
 * with ids. Every byte outside the rewritten tokens, including each terminator, is kept;
 * a block comment becomes one sigil line per text line at the block's indent.
 */
export function convertComments(path: string, source: string, comments: readonly ScannedComment[]): string {
  const spec = languageForPath(path);
  if (!spec) return source;
  const sigil = spec.lineSigil;
  const lines = splitLines(source);
  const fallbackEol = dominantEol(source);
  const splices: Splice[] = [];
  for (const c of comments) {
    if (c.protected) throw new Error(`refusing to convert a protected comment (${c.protected}) at ${path}:${c.line}`);
    const as = (text: string) => (text ? `${sigil} ${text}` : sigil);
    if (c.style === "line") {
      for (const span of c.spans) splices.push({ ...span, text: as(lineText(source.slice(span.start, span.end))) });
      continue;
    }
    const body = blockLines(source.slice(c.start, c.end));
    if (c.placement === "trailing") {
      splices.push({ start: c.start, end: c.end, text: as(body.join(" ")) });
      continue;
    }
    const row = lines[lineIndexAt(lines, c.start)]!;
    const eol = row.end > row.contentEnd ? source.slice(row.contentEnd, row.end) : fallbackEol;
    splices.push({ start: c.start, end: c.end, text: body.map((l, i) => (i ? eol + c.indent : "") + as(l)).join("") });
  }
  return applySplices(source, splices);
}
